# Generated by Django 4.2.4 on 2024-07-02 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netsooapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
